name: tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
        run: make install
      - name: test
        run: make test
      - name: linter
        run: make lint
