name: tests
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: make install
      - name: linter
        run: make lint
      - name: test
        run: make test
      - name: cc_coverage
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          run: make test-coverage

  