name: tests
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: make install
      - name: linter
        run: make lint
      - name: test
        run: make test
  